version: 2
services:
  todoApp:
    image: johscheuer/todo-app-web:v1
    ports:
     - "3000"
    depends_on:
     - redis-master
     - redis-slave
  redis-slave:
    image: johscheuer/redis-slave:v1
    depends_on:
     - redis-master
  redis-master:
    image: redis

networks:
  default:
    driver: bridge
