version: "2"
services:
  todoApp:
    image: johscheuer/todo-app-web:v2
    ports:
     - "3000"
    depends_on:
     - redis-master
     - redis-slave
  redis-slave:
    image: johscheuer/redis-slave:v2
    depends_on:
     - redis-master
  redis-master:
    image: johscheuer/redis-master:v2

networks:
  default:
    external:
      name: todoapp_network
